version: '3'
services:
  api:
    build: .
    env_file:
      - ./configuration/development.env
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports: 
      - 27017:27017
volumes:
  data:
