version: '3'
services:
  server:
    image: engage-server
    env_file:
      - ./production.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports: 
      - 27017:27017
volumes:
  data:
