version: '3'
services:
  api:
    build: .
    environment:
      - PORT=8081
      - COURSE_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - course
  course:
    build: .
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports: 
      - 27017:27017
volumes:
  data:
  