version: '3'
services:
  course:
    build: ../course-service
    ports:
      - 5656:5656
    environment:
      - PORT=5656
    depends_on:
      - mongo
  api:
    build: .
    environment:
      - PORT=8081
      - COURSE_PORT=5656
    ports:
      - 8081:8081
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - course
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports: 
      - '27017:27017'
volumes:
  data:
